---
- name: Ensure .bash_aliases file exists
  file:
    path: /home/{{ new_user }}/.bash_aliases
    state: touch
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: '0644'

- name: Add aliases to .bash_aliases
  lineinfile:
    path: /home/{{ new_user }}/.bash_aliases
    create: yes
    line: "{{ item }}"
  with_items:
    - "alias gst='git status'"
    - "alias glg='git log --stat'"
    - "alias glgp='git log --stat --patch'"
    - "alias gd='git diff'"
    - "alias dps='docker ps --format=\"table {{'{{'}}.Image{{'}}'}}\\t{{'{{'}}.RunningFor{{'}}'}}\\t{{'{{'}}.Status{{'}}'}}\\t{{'{{'}}.Names{{'}}'}}\"'"

- name: Source .bash_aliases in .bashrc
  lineinfile:
    path: /home/{{ new_user }}/.bashrc
    line: 'if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi'
    create: yes
    state: present
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: '0644'
