---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - make
      - curl
      - rsync
      - wget
      - git
      - htop
      - vim
    state: present
