---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH connections
  ufw:
    rule: allow
    port: 22

- name: Allow Mosh
  ufw:
    rule: allow
    proto: udp
    port: 60000:61000

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
